# Summer Products Data Analysis

#### 1. Importing Libraries

#### 2. Loading the Dataset

#### 3. Understanding the Dataset

#### 4. Data Quality Assessment

#### 5. Data Cleaning

#### 6. Exploratory Data Analysis

#### 7. Statistical Analysis

#### 8. Data Visualization

#### 9. Correlation Analysis

#### 10. Final Insights

In [2]:
import pandas as pd #the primary Python library for tabular data manipulation

In [3]:
#loading the csv file
df = pd.read_csv("/Users/jayraj/Desktop/College/Summer_Product_Analysis/Retail-Sales-Analytics/data/raw/summer-products_2020-08.csv")

In [4]:
#for confirmation that it has been loaded:
df.head() #this shows the first 5 values of the dataset

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,EUR,100,0,3.76,54,26.0,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22,EUR,20000,1,3.45,6135,2269.0,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,8.00,43,EUR,100,0,3.57,14,5.0,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8,EUR,5000,1,4.03,579,295.0,...,23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,Femmes Shorts d'été à lacets taille élastique ...,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3,EUR,100,1,3.10,20,6.0,...,14482,4.001588,5ab3b592c3911a095ad5dadb,0,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08

In [5]:
#looking at the last rows
df.tail()

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
1568,Nouvelle Mode Femmes Bohême Pissenlit Imprimer...,New Fashion Women Bohemia Dandelion Print Tee ...,6.0,9,EUR,10000,1,4.08,1367,722.0,...,5316,4.224605,5b507899ab577736508a0782,0,NaN,https://www.wish.com/c/5d5fadc99febd9356cbc52ee,https://contestimg.wish.com/api/webimage/5d5fa...,5d5fadc99febd9356cbc52ee,summer,2020-08
1569,10 couleurs femmes shorts d'été lacent ceintur...,10 Color Women Summer Shorts Lace Up Elastic W...,2.0,56,EUR,100,1,3.07,28,11.0,...,4435,3.696054,54d83b6b6b8a771e478558de,0,NaN,https://www.wish.com/c/5eccd22b4497b86fd48f16b4,https://contestimg.wish.com/api/webimage/5eccd...,5eccd22b4497b86fd48f16b4,summer,2020-08
1570,Nouveautés Hommes Siwmwear Beach-Shorts Hommes...,New Men Siwmwear Beach-Shorts Men Summer Quick...,5.0,19,EUR,100,0,3.71,59,24.0,...,210,3.961905,5b42da1bf64320209fc8da69,0,NaN,https://www.wish.com/c/5e74be96034d613d42b52dfe,https://contestimg.wish.com/api/webimage/5e74b...,5e74be96034d613d42b52dfe,summer,2020-08
1571,Mode femmes d'été sans manches robes col en V ...,Fashion Women Summer Sleeveless Dresses V Neck...,13.0,11,EUR,100,0,2.50,2,0.0,...,31,3.774194,5d56b32c40defd78043d5af9,0,NaN,https://www.wish.com/c/5eda07ab0e295c2097c36590,https://contestimg.wish.com/api/webimage/5eda0...,5eda07ab0e295c2097c36590,summer,2020-08
1572,Pantalon de yoga pour femmes à la mode Slim Fi...,Fashion Women Yoga Pants Slim Fit Fitness Runn...,7.0,6,EUR,100,1,4.07,14,8.0,...,7023,4.235939,5a409cf87b584e7951b2e25f,0,NaN,https://www.wish.com/c/5e857321f53c3d2d8f25e7ed,https://contestimg.wish.com/api/webimage/5e857...,5e857321f53c3d2d8f25e7ed,summer,2020-08

In [6]:
df.sample(5) #this gives us any random 5 values

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
1011,Nouveaux culottes d'été en tricot sans manches...,New Summer Women Sexy Sleeveless Knit Crop Tops,4.00,4,EUR,10000,0,4.03,2150,1115.0,...,230951,4.311066,53f2db3c104dae6bcae0c271,0,NaN,https://www.wish.com/c/599624c59e41a0342218c883,https://contestimg.wish.com/api/webimage/59962...,599624c59e41a0342218c883,summer,2020-08
919,Nouveau Mode Femmes Bavoir D'été Pantalon Shor...,New Fashion Women Summer Bib Pants Shorts Casu...,11.00,10,EUR,5000,1,3.20,249,85.0,...,88193,4.080891,5533c83986ff95173dc017d0,1,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/5d27f983780e69046e93254c,https://contestimg.wish.com/api/webimage/5d27f...,5d27f983780e69046e93254c,summer,2020-08
1431,S-8XL 2018 New Women Summer Casual Shirt Beach...,S-8XL 2018 New Women Summer Casual Shirt Beach...,8.00,7,EUR,20000,0,3.92,3080,1542.0,...,11854,4.094905,5800a8bb50d8ab5aaee15f20,0,NaN,https://www.wish.com/c/5b42cb780cb47619a7f6bbc2,https://contestimg.wish.com/api/webimage/5b42c...,5b42cb780cb47619a7f6bbc2,summer,2020-08
1155,2019 Nouveau Style Mode D'été Femmes Casual On...,2019 New Style Summer Fashion Women Casual One...,8.00,9,EUR,100,0,3.38,94,34.0,...,4955,4.005247,5b18eb98dfc31f2100f4c4cd,0,NaN,https://www.wish.com/c/5c355a86211ca154535af293,https://contestimg.wish.com/api/webimage/5c355...,5c355a86211ca154535af293,summer,2020-08
924,Tissu taille formateur gilet chaud shaper été ...,Fabric Waist Trainer Vest Hot Shaper Summer Sh...,5.66,6,EUR,100,0,3.08,13,3.0,...,2782,4.069015,583da4b58108913e6c79a32e,0,NaN,https://www.wish.com/c/5eb0b91db0d5d210fe8ac2ff,https://contestimg.wish.com/api/webimage/5eb0b...,5eb0b91db0d5d210fe8ac2ff,summer,2020-08

In [7]:
#to find the dimension of dataset, rows and columns
df.shape

(1573, 43)

In [8]:
# to get column names
df.columns.tolist() #here tolist help us to organize the data in a list format

['title',
 'title_orig',
 'price',
 'retail_price',
 'currency_buyer',
 'units_sold',
 'uses_ad_boosts',
 'rating',
 'rating_count',
 'rating_five_count',
 'rating_four_count',
 'rating_three_count',
 'rating_two_count',
 'rating_one_count',
 'badges_count',
 'badge_local_product',
 'badge_product_quality',
 'badge_fast_shipping',
 'tags',
 'product_color',
 'product_variation_size_id',
 'product_variation_inventory',
 'shipping_option_name',
 'shipping_option_price',
 'shipping_is_express',
 'countries_shipped_to',
 'inventory_total',
 'has_urgency_banner',
 'urgency_text',
 'origin_country',
 'merchant_title',
 'merchant_name',
 'merchant_info_subtitle',
 'merchant_rating_count',
 'merchant_rating',
 'merchant_id',
 'merchant_has_profile_picture',
 'merchant_profile_picture',
 'product_url',
 'product_picture',
 'product_id',
 'theme',
 'crawl_month']

In [9]:
#inspect data_types
df.dtypes

title                               str
title_orig                          str
price                           float64
retail_price                      int64
currency_buyer                      str
units_sold                        int64
uses_ad_boosts                    int64
rating                          float64
rating_count                      int64
rating_five_count               float64
rating_four_count               float64
rating_three_count              float64
rating_two_count                float64
rating_one_count                float64
badges_count                      int64
badge_local_product               int64
badge_product_quality             int64
badge_fast_shipping               int64
tags                                str
product_color                       str
product_variation_size_id           str
product_variation_inventory       int64
shipping_option_name                str
shipping_option_price             int64
shipping_is_express               int64
countries_shipped_to              int64
inventory_total                   int64
has_urgency_banner              float64
urgency_text                        str
origin_country                      str
merchant_title                      str
merchant_name                       str
merchant_info_subtitle              str
merchant_rating_count             int64
merchant_rating                 float64
merchant_id                         str
merchant_has_profile_picture      int64
merchant_profile_picture            str
product_url                         str
product_picture                     str
product_id                          str
theme                               str
crawl_month                         str
dtype: object

In [10]:
'''The first most imp command we should use. the info command'''
df.info()
#"I used info() to inspect the structure of the dataset, identify data types, and identify columns containing missing values."
# the df.info() tells us about some values being integers and float and others being textual and strings.
#This distinction will later determine which statistical methods and graphs we use.

<class 'pandas.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 43 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   title                         1573 non-null   str
 1   title_orig                    1573 non-null   str
 2   price                         1573 non-null   float64
 3   retail_price                  1573 non-null   int64
 4   currency_buyer                1573 non-null   str
 5   units_sold                    1573 non-null   int64
 6   uses_ad_boosts                1573 non-null   int64
 7   rating                        1573 non-null   float64
 8   rating_count                  1573 non-null   int64
 9   rating_five_count             1528 non-null   float64
 10  rating_four_count             1528 non-null   float64
 11  rating_three_count            1528 non-null   float64
 12  rating_two_count              1528 non-null   float64
 13  rating_one_count              1528 non-null   float64
 14  badges_count                  1573 non-null   int64
 15  badge_local_product           1573 non-null   int64
 16  badge_product_quality         1573 non-null   int64
 17  badge_fast_shipping           1573 non-null   int64
 18  tags                          1573 non-null   str
 19  product_color                 1532 non-null   str
 20  product_variation_size_id     1559 non-null   str
 21  product_variation_inventory   1573 non-null   int64
 22  shipping_option_name          1573 non-null   str
 23  shipping_option_price         1573 non-null   int64
 24  shipping_is_express           1573 non-null   int64
 25  countries_shipped_to          1573 non-null   int64
 26  inventory_total               1573 non-null   int64
 27  has_urgency_banner            473 non-null    float64
 28  urgency_text                  473 non-null    str
 29  origin_country                1556 non-null   str
 30  merchant_title                1573 non-null   str
 31  merchant_name                 1569 non-null   str
 32  merchant_info_subtitle        1572 non-null   str
 33  merchant_rating_count         1573 non-null   int64
 34  merchant_rating               1573 non-null   float64
 35  merchant_id                   1573 non-null   str
 36  merchant_has_profile_picture  1573 non-null   int64
 37  merchant_profile_picture      226 non-null    str
 38  product_url                   1573 non-null   str
 39  product_picture               1573 non-null   str
 40  product_id                    1573 non-null   str
 41  theme                         1573 non-null   str
 42  crawl_month                   1573 non-null   str
dtypes: float64(9), int64(15), str(19)
memory usage: 1.5 MB

In [11]:
'''Statistical overview'''
df.describe()

,price,retail_price,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,...,badge_fast_shipping,product_variation_inventory,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,merchant_rating_count,merchant_rating,merchant_has_profile_picture
count,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1528.000000,1528.000000,1528.000000,1528.000000,...,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,473.0,1.573000e+03,1573.000000,1573.000000
mean,8.325372,23.288620,4339.005086,0.432931,3.820896,889.659250,442.263743,179.599476,134.549738,63.711387,...,0.012715,33.081373,2.345200,0.002543,40.456453,49.821360,1.0,2.649583e+04,4.032345,0.143675
std,3.932030,30.357863,9356.539302,0.495639,0.515374,1983.928834,980.203270,400.516231,311.690656,151.343933,...,0.112075,21.353137,1.024371,0.050379,20.301203,2.562799,0.0,7.847446e+04,0.204768,0.350871
min,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,1.000000,0.000000,6.000000,1.000000,1.0,0.000000e+00,2.333333,0.000000
25%,5.810000,7.000000,100.000000,0.000000,3.550000,24.000000,12.000000,5.000000,4.000000,2.000000,...,0.000000,6.000000,2.000000,0.000000,31.000000,50.000000,1.0,1.987000e+03,3.917353,0.000000
50%,8.000000,10.000000,1000.000000,0.000000,3.850000,150.000000,79.000000,31.500000,24.000000,11.000000,...,0.000000,50.000000,2.000000,0.000000,40.000000,50.000000,1.0,7.936000e+03,4.040650,0.000000
75%,11.000000,26.000000,5000.000000,1.000000,4.110000,855.000000,413.500000,168.250000,129.250000,62.000000,...,0.000000,50.000000,3.000000,0.000000,43.000000,50.000000,1.0,2.456400e+04,4.161797,0.000000
max,49.000000,252.000000,100000.000000,1.000000,5.000000,20744.000000,11548.000000,4152.000000,3658.000000,2003.000000,...,1.000000,50.000000,12.000000,1.000000,140.000000,50.000000,1.0,2.174765e+06,5.000000,1.000000

In [12]:
#Categorical overview
df.describe(include="object")
#This gives us information about text/categorical columns.

/var/folders/60/ycmgjz8n0534kzc8j593kflh0000gn/T/ipykernel_13550/3029551298.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,title,title_orig,currency_buyer,tags,product_color,product_variation_size_id,shipping_option_name,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_id,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
count,1573,1573,1573,1573,1532,1559,1573,473,1556,1573,1569,1572,1573,226,1573,1573,1573,1573,1573
unique,1201,1203,1,1230,101,106,15,2,6,958,957,1058,958,125,1341,1341,1341,1,1
top,Nouvelle mode d'été femmes robe décontractée c...,New Fashion Summer Women Casual Dress Round Ne...,EUR,"Summer,Fashion,Necks,Skirts,Dress,Loose,Women'...",black,S,Livraison standard,Quantité limitée !,CN,guangzhouweishiweifushiyouxiangongsi,广州唯适唯服饰有限公司,"83 % avis positifs (32,168 notes)",558c2cdc89d53c4005ea2920,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/5c80e8a150c63d28c67b8f14,https://contestimg.wish.com/api/webimage/5c80e...,5c80e8a150c63d28c67b8f14,summer,2020-08
freq,24,24,1573,17,302,641,1508,472,1516,15,15,14,15,12,3,3,3,1573,1573

In [13]:
#we can also inspect
df["product_color"].value_counts()

product_color
black         302
white         254
yellow        105
blue           99
pink           99
             ...
violet          1
blackwhite      1
darkgreen       1
rosegold        1
gold            1
Name: count, Length: 101, dtype: int64

In [14]:
df.isnull().sum() #to find the null values

title                              0
title_orig                         0
price                              0
retail_price                       0
currency_buyer                     0
units_sold                         0
uses_ad_boosts                     0
rating                             0
rating_count                       0
rating_five_count                 45
rating_four_count                 45
rating_three_count                45
rating_two_count                  45
rating_one_count                  45
badges_count                       0
badge_local_product                0
badge_product_quality              0
badge_fast_shipping                0
tags                               0
product_color                     41
product_variation_size_id         14
product_variation_inventory        0
shipping_option_name               0
shipping_option_price              0
shipping_is_express                0
countries_shipped_to               0
inventory_total                    0
has_urgency_banner              1100
urgency_text                    1100
origin_country                    17
merchant_title                     0
merchant_name                      4
merchant_info_subtitle             1
merchant_rating_count              0
merchant_rating                    0
merchant_id                        0
merchant_has_profile_picture       0
merchant_profile_picture        1347
product_url                        0
product_picture                    0
product_id                         0
theme                              0
crawl_month                        0
dtype: int64

In [15]:
#creating a missing value summary
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum() / len(df)) * 100
})

missing = missing[missing["Missing Values"] > 0]

missing.sort_values(
    "Missing Values",
    ascending=False
)

                           Missing Values  Missing Percentage
merchant_profile_picture             1347           85.632549
has_urgency_banner                   1100           69.930070
urgency_text                         1100           69.930070
rating_five_count                      45            2.860776
rating_four_count                      45            2.860776
rating_three_count                     45            2.860776
rating_two_count                       45            2.860776
rating_one_count                       45            2.860776
product_color                          41            2.606484
origin_country                         17            1.080737
product_variation_size_id              14            0.890019
merchant_name                           4            0.254291
merchant_info_subtitle                  1            0.063573

In [16]:
# Now we will check duplicate rows
df.duplicated().sum()

np.int64(34)

In [17]:
#to check the actual duplicate row
df[df.duplicated()]

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
311,Women's Summer Fashion Spaghetti Strap Dress F...,Women's Summer Fashion Spaghetti Strap Dress F...,8.00,7,EUR,50,0,3.88,8,5.0,...,334,3.736527,5dda40561fead208515f98e2,0,NaN,https://www.wish.com/c/5ea91e4d29b81241e1d43b27,https://contestimg.wish.com/api/webimage/5ea91...,5ea91e4d29b81241e1d43b27,summer,2020-08
411,New Women Ladies Fashion Summer Skinny High Wa...,New Women Ladies Fashion Summer Skinny High Wa...,14.00,12,EUR,5000,1,4.06,643,365.0,...,80093,4.006692,583138b06339b410ab9663ec,0,NaN,https://www.wish.com/c/5c80e8a150c63d28c67b8f14,https://contestimg.wish.com/api/webimage/5c80e...,5c80e8a150c63d28c67b8f14,summer,2020-08
447,Womens Summer Fashion Lip Print 2pc Set Ladies...,Womens Summer Fashion Lip Print 2pc Set Ladies...,5.00,51,EUR,10,0,5.00,0,NaN,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5eb90ab5ad67f63678d15ed9,https://contestimg.wish.com/api/webimage/5eb90...,5eb90ab5ad67f63678d15ed9,summer,2020-08
505,Plus la taille des femmes de la mode lâche déc...,Plus Size Women's Fashion Loose Casual sleevel...,5.83,5,EUR,100,0,4.36,22,13.0,...,17471,3.952836,5aab3c8ea6bf7a704caec65c,0,NaN,https://www.wish.com/c/5e9932cab3eafb25c00ba79f,https://contestimg.wish.com/api/webimage/5e993...,5e9932cab3eafb25c00ba79f,summer,2020-08
571,Summer Women Fashion Fashion Robe courte sans ...,Summer Women Fashion Short Dress Sleeveless Wa...,8.00,51,EUR,100,0,4.29,31,19.0,...,5846,3.832535,5a792e56a71fbf471cf1fc99,0,NaN,https://www.wish.com/c/5d78eb19cc404c03393c83b5,https://contestimg.wish.com/api/webimage/5d78e...,5d78eb19cc404c03393c83b5,summer,2020-08
684,Femmes d'été Boho Maxi Polka Dot Robe Irréguli...,Summer Women Boho Maxi Polka Dot Dress Irregul...,6.00,6,EUR,100,1,3.67,27,9.0,...,4705,4.040595,580c7d0a8b67fa197454a2d1,0,NaN,https://www.wish.com/c/5e142dee04c3e579e89576a3,https://contestimg.wish.com/api/webimage/5e142...,5e142dee04c3e579e89576a3,summer,2020-08
689,Femmes d'été Mode Shorts de sport double couch...,Summer Women Fashion Double-Layer Sports Short...,3.76,7,EUR,50,0,3.50,8,4.0,...,3730,3.880429,58d8e8ebd929c652b9c04c05,0,NaN,https://www.wish.com/c/5ebe625c3cdb6c40b7b9231e,https://contestimg.wish.com/api/webimage/5ebe6...,5ebe625c3cdb6c40b7b9231e,summer,2020-08
698,Débardeur en coton sans manches pour femmes,Women's Summer Sleeveless Tank Cotton Vest Pri...,6.00,7,EUR,50,0,2.67,3,1.0,...,1374,4.058952,5a2fa9ce6ea4a770c66f5599,0,NaN,https://www.wish.com/c/5eb4f323b67a8d189a8f8380,https://contestimg.wish.com/api/webimage/5eb4f...,5eb4f323b67a8d189a8f8380,summer,2020-08
770,Nouvelle mode d'été femmes robe décontractée c...,New Fashion Summer Women Casual Dress Round Ne...,2.00,9,EUR,100,0,3.47,32,11.0,...,4856,4.167628,5710ac98b2d43a5925da8dd8,0,NaN,https://www.wish.com/c/5e940265ea3640c9ca0353aa,https://contestimg.wish.com/api/webimage/5e940...,5e940265ea3640c9ca0353aa,summer,2020-08
991,2020 Shorts classiques pour hommes d'été Panta...,2020 Summer Men's Classic Shorts Multi-pocket ...,7.00,17,EUR,10,0,5.00,2,2.0,...,46,3.608696,5e2ecb9deed5087a7ba2f5f7,0,NaN,https://www.wish.com/c/5eeef4c4066647a9388a8ac2,https://contestimg.wish.com/api/webimage/5eeef...,5eeef4c4066647a9388a8ac2,summer,2020-08
997,S-5XL Nouvelle Mode Femmes Tops Blouse Sans Ma...,S-5XL New Fashion Women Tops Blouse Sleeveless...,4.83,51,EUR,50,1,2.00,1,0.0,...,57,3.824561,5e3c5fbfe217d492138970c1,0,NaN,https://www.wish.com/c/5ee8875404718a4bba2d6348,https://contestimg.wish.com/api/webimage/5ee88...,5ee8875404718a4bba2d6348,summer,2020-08
1003,6 Couleurs Automne Été Dames Casual Lâche Soli...,6 Colors Autumn Summer Ladies Casual Loose Sol...,9.00,8,EUR,100,1,3.18,72,17.0,...,288,3.729167,5de0981739adf2a3406bed18,0,NaN,https://www.wish.com/c/5eaa6d9c8d99eb3ec06709f4,https://contestimg.wish.com/api/webimage/5eaa6...,5eaa6d9c8d99eb3ec06709f4,summer,2020-08
1050,Débardeur pour femme Débardeur Bandage Plume I...,Women Tops Tank Bandage Feather Print Sleevele...,3.00,3,EUR,100,1,4.29,58,36.0,...,1050,3.883810,5a698cef028bbd27227d3d12,0,NaN,https://www.wish.com/c/5cde56ea6bbbd86b1cbab4a8,https://contestimg.wish.com/api/webimage/5cde5...,5cde56ea6bbbd86b1cbab4a8,summer,2020-08
1074,Femmes d'été Mode Débardeurs Sexy Sans Manches...,Women Summer Fashion Tank Tops Sexy Sleeveless...,2.00,2,EUR,1000,0,4.19,81,50.0,...,126370,4.146957,58ad449708de0c6dc59d9e06,1,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/5e16cb87e6dd7c03be24b28a,https://contestimg.wish.com/api/webimage/5e16c...,5e16cb87e6dd7c03be24b28a,summer,2020-08
1109,Robe à bretelles lâche col en v pour femmes d'...,Summer Women's Loose V-neck Sling Dress Sleeve...,7.00,26,EUR,100,0,2.90,10,4.0,...,32,3.187500,5e54a05c207f9d3e6cee7040,0,NaN,https://www.wish.com/c/5e68ffbbe97f758d0698e049,https://contestimg.wish.com/api/webimage/5e68f...,5e68ffbbe97f758d0698e049,summer,2020-08
1138,NOUVELLES femmes manches courtes Baggy Summer ...,NEW Womens Short Sleeve Baggy Summer Beach Mid...,11.00,84,EUR,100,1,3.61,18,6.0,...,435,3.855172,5ac82ff62c49567ffa616535,0,NaN,https://www.wish.com/c/5e65d0ea5dc348884032a14e,https://contestimg.wish.com/api/webimage/5e65d...,5e65d0ea5dc348884032a14e,summer,2020-08
1173,Costume de sport cool pour hommes d'été Vêteme...,Summer mens cool sport suit Sports Wear Casual...,16.00,14,EUR,10,0,3.00,3,0.0,...,31,3.548387,5e61c817039ce2184a0ed392,0,NaN,https://www.wish.com/c/5e9a74e447f7d92c8db8d14b,https://contestimg.wish.com/api/webimage/5e9a7...,5e9a74e447f7d92c8db8d14b,summer,2020-08
1229,New Summer Women's New Fashion Sleeveless Polk...,New Summer Women's New Fashion Sleeveless Polk...,3.68,4,EUR,100,0,3.71,42,18.0,...,105015,3.789601,5177b0b63feb620dd802a197,0,NaN,https://www.wish.com/c/5d82f19340367911da1b9ee7,https://contestimg.wish.com/api/webimage/5d82f...,5d82f19340367911da1b9ee7,summer,2020-08
1251,Mini robe de soirée décontractée sans manches ...,Sexy Women's Summer Casual Sleeveless Evening ...,2.89,7,EUR,50,0,5.00,1,1.0,...,30,3.733333,5e535f1b397cba44cf1118d8,0,NaN,https://www.wish.com/c/5eba5b1c29367c77b5c0eb35,https://contestimg.wish.com/api/webimage/5eba5...,5eba5b1c29367c77b5c0eb35,summer,2020-08
1254,2020 Été Sexy Femmes Halter Tops Plage De Nata...,2020 Summer Sexy Women Halter Tops Beach Swimm...,7.00,6,EUR,100,0,3.60,25,10.0,...,483,4.155280,5d8b2f16ddac8e198fc7c8b7,0,NaN,https://www.wish.com/c/5dea1d9cec016f062ce8aab1,https://contestimg.wish.com/api/webimage/5dea1...,5dea1d9cec016f062ce8aab1,summer,2020-08
1262,Mode féminine d'été T-shirt à manches courtes ...,Summer Women's Fashion Short Sleeve T Shirt La...,1.72,2,EUR,100,1,3.77,30,15.0,...,32168,3.884544,558c2cdc89d53c4005ea2920,0,NaN,https://www.wish.com/c/5ebe0ead593b960eb1c82d0b,https://contestimg.wish.com/api/webimage/5ebe0...,5ebe0ead593b960eb1c82d0b,summer,2020-08
1271,"2019 été nouvelle mode féminine ""Let It ~"" Bee...",2019 Summer New Women Fashion “ Let It ~“ Bee ...,11.00,10,EUR,10000,1,4.05,1479,754.0,...,5816,3.936382,58330d7def56284f7634e5e5,0,NaN,https://www.wish.com/c/5cedf93ac0baab7389f4ccd7,https://contestimg.wish.com/api/webimage/5cedf...,5cedf93ac0baab7389f4ccd7,summer,2020-08
1316,Femmes été décontracté lâche couleur unie salo...,Women Summer Casual Loose Solid Color Vintage ...,11.00,11,EUR,1000,0,2.99,228,59.0,...,5264,4.032865,5aa78a0c75599a5bd049d682,0,NaN,https://www.wish.com/c/5d410e4a11512c51311ad3d3,https://contestimg.wish.com/api/webimage/5d410...,5d410e4a11512c51311ad3d3,summer,2020-08
1331,Femmes D'été Nouvelle Mode Shorts De Sport Cou...,Women's Summer New Fashion Sports Shorts Solid...,7.00,6,EUR,50,0,4.00,4,3.0,...,34,4.352941,5d4bbed57ad242352a46d910,0,NaN,https://www.wish.com/c/5ebff6d34a4cf4438dba5d80,https://contestimg.wish.com/api/webimage/5ebff...,5ebff6d34a4cf4438dba5d80,summer,2020-08
1346,Nouvelle mode d'été femmes robe décontractée c...,New Fashion Summer Women Casual Dress Round Ne...,1.68,2,EUR,100,1,3.67,12,6.0,...,1047,3.956065,56cd50871e15ff78c21de8a9,0,NaN,https://www.wish.com/c/5e93d60ebc5446aedde50c50,https://contestimg.wish.com/api/webimage/5e93d...,5e93d60ebc5446aedde50c50,summer,2020-08
1387,Mode d'été femme papillon réservoir gilet sans...,Summer fashion female butterfly tank vest slee...,6.00,33,EUR,10,0,2.33,3,1.0,...,32394,3.924677,57864d704d669274929898fb,0,NaN,https://www.wish.com/c/5eb4dd1bba09581b242c01b0,https://contestimg.wish.com/api/webimage/5eb4d...,5eb4dd1bba09581b242c01b0,summer,2020-08
1433,Robe de plage à manches courtes Femmes Robe d'...,Short Sleeve Beach Dress Women Summer Print V ...,8.00,10,EUR,50,0,5.00,2,2.0,...,127,3.874016,5eb51ed929e7865dc268a561,0,NaN,https://www.wish.com/c/5ec1e63f7abee20ab93c68f2,https://contestimg.wish.com/api/webimage/5ec1e...,5ec1e63f7abee20ab93c68f2,summer,2020-08
1436,Casual Boho Beach Robes Womens O-Neck Party Su...,Casual Boho Beach Dresses Womens O-Neck Party ...,8.00,7,EUR,100,1,3.00,11,3.0,...,5768,4.484397,58ff6866e17bc0302f540b50,0,NaN,https://www.wish.com/c/5ebf9b2a6e0bd84bbf5edb18,https://contestimg.wish.com/api/webimage/5ebf9...,5ebf9b2a6e0bd84bbf5edb18,summer,2020-08
1444,2019 Mode féminine Hot Summer Fashion Flare Sl...,2019 Women's Fashion Hot Summer Fashion Flare ...,11.00,10,EUR,100,0,3.96,98,46.0,...,5070,4.276726,5ae2d62f2c49564f1df9bbd1,0,NaN,https://www.wish.com/c/5cbdabea787e5828c3059a6c,https://contestimg.wish.com/api/webimage/5cbda...,5cbdabea787e5828c3059a6c,summer,2020-08
1479,Mode d'été femme papillon réservoir gilet sans...,Summer fashion female butterfly tank vest slee...,7.00,33,EUR,50,0,3.00,2,0.0,...,25222,4.001546,566a47bfe9fa8a31b3ef5141,0,NaN,https://www.wish.com/c/5eb4dd169263020a42be1a88,https://contestimg.wish.com/api/webimage/5eb4d...,5eb4dd169263020a42be1a88,summer,2020-08
1481,Mode féminine été bretelles spaghetti imprimé ...,Women's Summer Fashion Spaghetti Strap Floral ...,8.00,68,EUR,8,0,5.00,0,NaN,...,626,3.916933,5d3aa36072b0c915fe6b8fbd,0,NaN,https://www.wish.com/c/5eb2200b989caa081980b812,https://contestimg.wish.com/api/webimage/5eb22...,5eb2200b989caa081980b812,summer,2020-08
1491,Costume de sport cool pour hommes d'été Vêteme...,Summer mens cool sport suit Sports Wear Casual...,11.00,168,EUR,10,0,3.33,3,0.0,...,47,3.914894,5e71bc2ff2bef60050bd3a86,0,NaN,https://www.wish.com/c/5e9dad8cbc19c300417e1733,https://contestimg.wish.com/api/webimage/5e9da...,5e9dad8cbc19c300417e1733,summer,2020-08
1512,Mode féminine sans manches asymétrique Hippie ...,Women's Fashion Sleeveless Asymmetric Hippie S...,5.84,5,EUR,100,0,4.04,24,12.0,...,9470,3.956811,5952a218e81e8a4c30b5bbbc,0,NaN,https://www.wish.com/c/5eb10d32f12bf74120b0fd1e,https://contestimg.wish.com/api/webimage/5eb10...,5eb10d32f12bf74120b0fd1e,summer,2020-08
1553,Chemisiers sans manches d'été pour femmes Casu...,Women's Summer Sleeveless Blouses Casual Sling...,6.00,6,EUR,100,0,3.40,5,2.0,...,112,3.625000,5dc40e313710b91b0f04fcc5,0,NaN,https://www.wish.com/c/5eba05b08c884a0bddd0ad96,https://contestimg.wish.com/api/webimage/5eba0...,5eba05b08c884a0bddd0ad96,summer,2020-08

In [18]:
# Checking unique values
# now we need to understand our categorical values
# this tells us about how many diff categories exist in each text column
categorical_columns = df.select_dtypes(
    include="object"
).columns

for column in categorical_columns:
    print(f"\n{column}")
    print("Unique values:", df[column].nunique())

title
Unique values: 1201

title_orig
Unique values: 1203

currency_buyer
Unique values: 1

tags
Unique values: 1230

product_color
Unique values: 101

product_variation_size_id
Unique values: 106

shipping_option_name
Unique values: 15

urgency_text
Unique values: 2

origin_country
Unique values: 6

merchant_title
Unique values: 958

merchant_name
Unique values: 957

merchant_info_subtitle
Unique values: 1058

merchant_id
Unique values: 958

merchant_profile_picture
Unique values: 125

product_url
Unique values: 1341

product_picture
Unique values: 1341

product_id
Unique values: 1341

theme
Unique values: 1

crawl_month
Unique values: 1

/var/folders/60/ycmgjz8n0534kzc8j593kflh0000gn/T/ipykernel_13550/2022998581.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(

In [19]:
# Inspecting important categorical columns
print(df["product_color"].value_counts(dropna=False).head(20))
print("------") #I added this line so that the outputs can be seen separately
print(df["shipping_option_name"].value_counts(dropna=False))
print("------")
print(df["currency_buyer"].value_counts(dropna=False))
print("------")
print(df["theme"].value_counts(dropna=False))

product_color
black            302
white            254
yellow           105
blue              99
pink              99
red               93
green             90
grey              71
purple            53
NaN               41
armygreen         31
navyblue          28
winered           28
orange            27
multicolor        20
beige             14
lightblue         12
khaki             12
gray              11
white & green     10
Name: count, dtype: int64
------
shipping_option_name
Livraison standard         1508
Standard Shipping            21
Envio Padrão                  9
Expediere Standard            6
Envío normal                  5
الشحن القياسي                 4
Standardversand               3
Standardowa wysyłka           3
Livraison Express             3
Стандартная доставка          3
Standart Gönderi              2
การส่งสินค้ามาตรฐาน           2
Spedizione standard           2
ការដឹកជញ្ជូនតាមស្តង់ដារ       1
Ekspresowa wysyłka            1
Name: count, dtype: int64
------
currency_buyer
EUR    1573
Name: count, dtype: int64
------
theme
summer    1573
Name: count, dtype: int64

In [20]:
#Check Numerical Columns for Suspicious Values
# To explicitly identify the numerical columns:
numeric_columns = df.select_dtypes(
    include="number"
).columns

print(numeric_columns.tolist())
print("-----------------------------------------")

#To check for negative values
(df[numeric_columns] < 0).sum()

['price', 'retail_price', 'units_sold', 'uses_ad_boosts', 'rating', 'rating_count', 'rating_five_count', 'rating_four_count', 'rating_three_count', 'rating_two_count', 'rating_one_count', 'badges_count', 'badge_local_product', 'badge_product_quality', 'badge_fast_shipping', 'product_variation_inventory', 'shipping_option_price', 'shipping_is_express', 'countries_shipped_to', 'inventory_total', 'has_urgency_banner', 'merchant_rating_count', 'merchant_rating', 'merchant_has_profile_picture']
-----------------------------------------

price                           0
retail_price                    0
units_sold                      0
uses_ad_boosts                  0
rating                          0
rating_count                    0
rating_five_count               0
rating_four_count               0
rating_three_count              0
rating_two_count                0
rating_one_count                0
badges_count                    0
badge_local_product             0
badge_product_quality           0
badge_fast_shipping             0
product_variation_inventory     0
shipping_option_price           0
shipping_is_express             0
countries_shipped_to            0
inventory_total                 0
has_urgency_banner              0
merchant_rating_count           0
merchant_rating                 0
merchant_has_profile_picture    0
dtype: int64

In [21]:
#Check rating validity
print(df["rating"].unique())
print("------------------------------------------------")
print(
    df[
        (df["rating"] < 1) |
        (df["rating"] > 5)
    ]
)
#the "Empty data frame would tell us there aren't ratings outside the expected range."

[3.76 3.45 3.57 4.03 3.1  5.   3.84 3.47 3.6  3.46 3.31 3.32 3.65 3.92
 3.72 3.83 3.82 3.67 3.38 3.75 4.15 4.29 4.25 4.06 4.37 3.81 3.44 3.8
 4.16 2.75 4.26 1.5  3.79 3.53 3.28 3.   3.18 3.43 4.19 3.5  3.56 4.
 4.13 3.91 2.71 3.93 3.41 3.74 4.5  4.24 4.22 3.42 3.64 3.08 4.41 3.7
 3.94 4.07 4.1  3.77 4.54 4.11 3.96 2.8  3.89 3.97 3.61 4.2  2.61 4.3
 4.12 3.71 4.75 3.59 3.99 3.73 4.38 3.78 4.05 4.6  4.04 3.49 3.07 3.11
 3.19 2.5  2.92 3.68 3.63 3.06 2.67 3.29 2.   4.14 3.14 3.98 3.35 4.09
 3.4  4.31 3.69 3.01 4.17 2.81 4.02 4.57 3.16 4.44 3.52 4.23 4.21 4.28
 3.9  3.54 3.33 4.01 3.85 3.25 3.39 3.66 3.88 3.09 3.34 4.39 3.86 3.58
 4.32 4.33 1.   3.13 2.99 4.47 3.2  2.82 3.3  4.34 3.62 3.95 4.35 4.36
 3.51 4.08 3.12 4.86 4.62 2.95 3.23 3.15 3.37 3.55 4.63 4.27 4.74 4.4
 2.25 2.88 3.26 3.21 3.48 3.17 2.79 4.53 2.93 2.9  4.18 3.87 2.57 4.67
 4.83 2.98 3.22 4.52 4.46 3.27 2.33 3.36 2.7  3.04 2.97 4.58 4.43 2.44
 3.24 3.03 2.86 2.94 4.8  4.55 4.45 2.77 4.48 4.64]
------------------------------------------------
Empty DataFrame
Columns: [title, title_orig, price, retail_price, currency_buyer, units_sold, uses_ad_boosts, rating, rating_count, rating_five_count, rating_four_count, rating_three_count, rating_two_count, rating_one_count, badges_count, badge_local_product, badge_product_quality, badge_fast_shipping, tags, product_color, product_variation_size_id, product_variation_inventory, shipping_option_name, shipping_option_price, shipping_is_express, countries_shipped_to, inventory_total, has_urgency_banner, urgency_text, origin_country, merchant_title, merchant_name, merchant_info_subtitle, merchant_rating_count, merchant_rating, merchant_id, merchant_has_profile_picture, merchant_profile_picture, product_url, product_picture, product_id, theme, crawl_month]
Index: []

[0 rows x 43 columns]

In [22]:
# Checking price validity
#we are checking if there are zero or negative pricing
#empty dataframe means it is correct

print(
    df[
        (df["price"] <= 0) |
        (df["retail_price"] <= 0)
    ][["price", "retail_price"]]
)

Empty DataFrame
Columns: [price, retail_price]
Index: []

In [23]:
# Checking sales vlaidity
# Again i am checking ig dataset contains impossible values
print(
    df[df["units_sold"] < 0][["title", "units_sold"]]
)

Empty DataFrame
Columns: [title, units_sold]
Index: []

In [24]:
# A. MISSING VALUE SUMMARY
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum() / len(df)) * 100
})

missing = missing[missing["Missing Values"] > 0]

missing.sort_values(
    "Missing Values",
    ascending=False
)

                           Missing Values  Missing Percentage
merchant_profile_picture             1347           85.632549
has_urgency_banner                   1100           69.930070
urgency_text                         1100           69.930070
rating_five_count                      45            2.860776
rating_four_count                      45            2.860776
rating_three_count                     45            2.860776
rating_two_count                       45            2.860776
rating_one_count                       45            2.860776
product_color                          41            2.606484
origin_country                         17            1.080737
product_variation_size_id              14            0.890019
merchant_name                           4            0.254291
merchant_info_subtitle                  1            0.063573

In [25]:
#B. DUPLICATES CHECK
df.duplicated().sum()

np.int64(34)

In [26]:
#C. PRODUCT ID CHECK 
print("Duplicate Product IDs:", df["product_id"].duplicated().sum())
print("Unique Product IDs:", df["product_id"].nunique())

Duplicate Product IDs: 232
Unique Product IDs: 1341

In [27]:
#D. CATEGORICAL INSPECTION
print(df["product_color"].value_counts(dropna=False).head(20))
print("--------------------------------------------------")
print(df["shipping_option_name"].value_counts(dropna=False))
print("--------------------------------------------------")

print(df["currency_buyer"].value_counts(dropna=False))
print("--------------------------------------------------")

print(df["theme"].value_counts(dropna=False))
print("--------------------------------------------------")

product_color
black            302
white            254
yellow           105
blue              99
pink              99
red               93
green             90
grey              71
purple            53
NaN               41
armygreen         31
navyblue          28
winered           28
orange            27
multicolor        20
beige             14
lightblue         12
khaki             12
gray              11
white & green     10
Name: count, dtype: int64
--------------------------------------------------
shipping_option_name
Livraison standard         1508
Standard Shipping            21
Envio Padrão                  9
Expediere Standard            6
Envío normal                  5
الشحن القياسي                 4
Standardversand               3
Standardowa wysyłka           3
Livraison Express             3
Стандартная доставка          3
Standart Gönderi              2
การส่งสินค้ามาตรฐาน           2
Spedizione standard           2
ការដឹកជញ្ជូនតាមស្តង់ដារ       1
Ekspresowa wysyłka            1
Name: count, dtype: int64
--------------------------------------------------
currency_buyer
EUR    1573
Name: count, dtype: int64
--------------------------------------------------
theme
summer    1573
Name: count, dtype: int64
--------------------------------------------------

In [28]:
#E. INVALID NUMERICAL VALUES
numeric_columns = df.select_dtypes(include="number").columns

print((df[numeric_columns] < 0).sum())

price                           0
retail_price                    0
units_sold                      0
uses_ad_boosts                  0
rating                          0
rating_count                    0
rating_five_count               0
rating_four_count               0
rating_three_count              0
rating_two_count                0
rating_one_count                0
badges_count                    0
badge_local_product             0
badge_product_quality           0
badge_fast_shipping             0
product_variation_inventory     0
shipping_option_price           0
shipping_is_express             0
countries_shipped_to            0
inventory_total                 0
has_urgency_banner              0
merchant_rating_count           0
merchant_rating                 0
merchant_has_profile_picture    0
dtype: int64

In [29]:
#F. RATING VALIDATION
print(
    df[
        (df["rating"] < 1) |
        (df["rating"] > 5)
    ]
)

Empty DataFrame
Columns: [title, title_orig, price, retail_price, currency_buyer, units_sold, uses_ad_boosts, rating, rating_count, rating_five_count, rating_four_count, rating_three_count, rating_two_count, rating_one_count, badges_count, badge_local_product, badge_product_quality, badge_fast_shipping, tags, product_color, product_variation_size_id, product_variation_inventory, shipping_option_name, shipping_option_price, shipping_is_express, countries_shipped_to, inventory_total, has_urgency_banner, urgency_text, origin_country, merchant_title, merchant_name, merchant_info_subtitle, merchant_rating_count, merchant_rating, merchant_id, merchant_has_profile_picture, merchant_profile_picture, product_url, product_picture, product_id, theme, crawl_month]
Index: []

[0 rows x 43 columns]

In [30]:
#G. PRICE VALIDATION
print(
    df[
        (df["price"] <= 0) |
        (df["retail_price"] <= 0)
    ][["price", "retail_price"]]
)

Empty DataFrame
Columns: [price, retail_price]
Index: []

In [31]:
#H. SALES VLAIDATION
print(
    df[df["units_sold"] < 0][["title", "units_sold"]]
)

Empty DataFrame
Columns: [title, units_sold]
Index: []

In [ ]:
#3.10 TO INVESTIGATE DUPLICATE PRODUCT IDS
duplicate_ids = df[
    df["product_id"].duplicated(keep=False)
].sort_values("product_id")

duplicate_ids[
    [
        "product_id",
        "title",
        "price",
        "retail_price",
        "units_sold",
        "rating"
    ]
]

#With keep = False we see every row belonging to a repeated product id. This is what we need for investigation

,product_id,title,price,retail_price,units_sold,rating
954,5577faf03cef83230c39d0c3,Mode Femmes Blanc D'été Boho Sexy Dentelle Cre...,11.0,10,10000,3.75
1179,5577faf03cef83230c39d0c3,Mode Femmes Blanc D'été Boho Sexy Dentelle Cre...,11.0,10,10000,3.75
137,57639e8824841762459c5e5c,Maillots de bain à rayures pour dames avec dou...,8.0,7,20000,4.05
962,57639e8824841762459c5e5c,Maillots de bain à rayures pour dames avec dou...,8.0,7,20000,4.05
851,58db2a4eca5fec55a2b176a8,S-5XL Summer Women Casual Tops Off Shoulder Fa...,9.0,65,1000,4.09
...,...,...,...,...,...,...
991,5eeef4c4066647a9388a8ac2,2020 Shorts classiques pour hommes d'été Panta...,7.0,17,10,5.00
312,5ef0ef11f30aba4e22166d4b,Summer New Europe and The United States Sexy R...,8.0,26,100,5.00
846,5ef0ef11f30aba4e22166d4b,Summer New Europe and The United States Sexy R...,8.0,26,100,5.00
555,5f03643cc00703c46d6745f0,Femmes Robes D'été De Mode Col En V Dos Nu Rob...,12.0,11,100,5.00
1148,5f03643cc00703c46d6745f0,Femmes Robes D'été De Mode Col En V Dos Nu Rob...,12.0,11,100,5.00

In [33]:
# 3.11 COUNT HOW MANY TIMES PRODUCTS REPEAT
df["product_id"].value_counts().head(20)

product_id
5c80e8a150c63d28c67b8f14    3
5e9a74e447f7d92c8db8d14b    3
5ebff6d34a4cf4438dba5d80    3
5ebe0ead593b960eb1c82d0b    3
5eaa6d9c8d99eb3ec06709f4    3
5eb4dd169263020a42be1a88    3
5dea1d9cec016f062ce8aab1    3
5e93d60ebc5446aedde50c50    3
5eb4f323b67a8d189a8f8380    3
5e142dee04c3e579e89576a3    3
5ec1e63f7abee20ab93c68f2    3
5ee8875404718a4bba2d6348    3
5cde56ea6bbbd86b1cbab4a8    3
5ea91e4d29b81241e1d43b27    3
5e9932cab3eafb25c00ba79f    3
5e9dad8cbc19c300417e1733    3
5e16cb87e6dd7c03be24b28a    3
5eb2200b989caa081980b812    3
5cedf93ac0baab7389f4ccd7    3
5eba05b08c884a0bddd0ad96    3
Name: count, dtype: int64

In [34]:
# 3.12 INVESTIGATE THE 34 EXACT DUPLICATES
exact_duplicates = df[df.duplicated(keep=False)]

exact_duplicates.sort_values(
    by="product_id"
)

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
37,New Women Ladies Fashion Summer Skinny High Wa...,New Women Ladies Fashion Summer Skinny High Wa...,14.00,12,EUR,5000,1,4.06,643,365.0,...,80093,4.006692,583138b06339b410ab9663ec,0,NaN,https://www.wish.com/c/5c80e8a150c63d28c67b8f14,https://contestimg.wish.com/api/webimage/5c80e...,5c80e8a150c63d28c67b8f14,summer,2020-08
411,New Women Ladies Fashion Summer Skinny High Wa...,New Women Ladies Fashion Summer Skinny High Wa...,14.00,12,EUR,5000,1,4.06,643,365.0,...,80093,4.006692,583138b06339b410ab9663ec,0,NaN,https://www.wish.com/c/5c80e8a150c63d28c67b8f14,https://contestimg.wish.com/api/webimage/5c80e...,5c80e8a150c63d28c67b8f14,summer,2020-08
557,2019 Mode féminine Hot Summer Fashion Flare Sl...,2019 Women's Fashion Hot Summer Fashion Flare ...,11.00,10,EUR,100,0,3.96,98,46.0,...,5070,4.276726,5ae2d62f2c49564f1df9bbd1,0,NaN,https://www.wish.com/c/5cbdabea787e5828c3059a6c,https://contestimg.wish.com/api/webimage/5cbda...,5cbdabea787e5828c3059a6c,summer,2020-08
1444,2019 Mode féminine Hot Summer Fashion Flare Sl...,2019 Women's Fashion Hot Summer Fashion Flare ...,11.00,10,EUR,100,0,3.96,98,46.0,...,5070,4.276726,5ae2d62f2c49564f1df9bbd1,0,NaN,https://www.wish.com/c/5cbdabea787e5828c3059a6c,https://contestimg.wish.com/api/webimage/5cbda...,5cbdabea787e5828c3059a6c,summer,2020-08
289,Débardeur pour femme Débardeur Bandage Plume I...,Women Tops Tank Bandage Feather Print Sleevele...,3.00,3,EUR,100,1,4.29,58,36.0,...,1050,3.883810,5a698cef028bbd27227d3d12,0,NaN,https://www.wish.com/c/5cde56ea6bbbd86b1cbab4a8,https://contestimg.wish.com/api/webimage/5cde5...,5cde56ea6bbbd86b1cbab4a8,summer,2020-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1433,Robe de plage à manches courtes Femmes Robe d'...,Short Sleeve Beach Dress Women Summer Print V ...,8.00,10,EUR,50,0,5.00,2,2.0,...,127,3.874016,5eb51ed929e7865dc268a561,0,NaN,https://www.wish.com/c/5ec1e63f7abee20ab93c68f2,https://contestimg.wish.com/api/webimage/5ec1e...,5ec1e63f7abee20ab93c68f2,summer,2020-08
217,S-5XL Nouvelle Mode Femmes Tops Blouse Sans Ma...,S-5XL New Fashion Women Tops Blouse Sleeveless...,4.83,51,EUR,50,1,2.00,1,0.0,...,57,3.824561,5e3c5fbfe217d492138970c1,0,NaN,https://www.wish.com/c/5ee8875404718a4bba2d6348,https://contestimg.wish.com/api/webimage/5ee88...,5ee8875404718a4bba2d6348,summer,2020-08
997,S-5XL Nouvelle Mode Femmes Tops Blouse Sans Ma...,S-5XL New Fashion Women Tops Blouse Sleeveless...,4.83,51,EUR,50,1,2.00,1,0.0,...,57,3.824561,5e3c5fbfe217d492138970c1,0,NaN,https://www.wish.com/c/5ee8875404718a4bba2d6348,https://contestimg.wish.com/api/webimage/5ee88...,5ee8875404718a4bba2d6348,summer,2020-08
789,2020 Shorts classiques pour hommes d'été Panta...,2020 Summer Men's Classic Shorts Multi-pocket ...,7.00,17,EUR,10,0,5.00,2,2.0,...,46,3.608696,5e2ecb9deed5087a7ba2f5f7,0,NaN,https://www.wish.com/c/5eeef4c4066647a9388a8ac2,https://contestimg.wish.com/api/webimage/5eeef...,5eeef4c4066647a9388a8ac2,summer,2020-08
991,2020 Shorts classiques pour hommes d'été Panta...,2020 Summer Men's Classic Shorts Multi-pocket ...,7.00,17,EUR,10,0,5.00,2,2.0,...,46,3.608696,5e2ecb9deed5087a7ba2f5f7,0,NaN,https://www.wish.com/c/5eeef4c4066647a9388a8ac2,https://contestimg.wish.com/api/webimage/5eeef...,5eeef4c4066647a9388a8ac2,summer,2020-08

In [35]:
#3.13 — Investigate the Urgency Columns
print(
    df["has_urgency_banner"].value_counts(dropna=False)
)

print(
    df["urgency_text"].value_counts(dropna=False)
)

print(
    pd.crosstab(
        df["has_urgency_banner"].isna(),
        df["urgency_text"].isna()
    )
)

has_urgency_banner
NaN    1100
1.0     473
Name: count, dtype: int64
urgency_text
NaN                                 1100
Quantité limitée !                   472
Réduction sur les achats en gros       1
Name: count, dtype: int64
urgency_text        False  True
has_urgency_banner
False                 473      0
True                    0   1100

In [36]:
#3.14 — Investigate Rating Count Missingness
rating_missing = df[
    df["rating_five_count"].isna()
]

rating_missing[
    [
        "title",
        "rating",
        "rating_count",
        "rating_five_count",
        "rating_four_count",
        "rating_three_count",
        "rating_two_count",
        "rating_one_count"
    ]
]

,title,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count
74,Fashion Women Sleeveless Lace Vest Loose V Nec...,5.0,0,NaN,NaN,NaN,NaN,NaN
112,Womens Summer Fashion Lip Print 2pc Set Ladies...,5.0,0,NaN,NaN,NaN,NaN,NaN
126,Women's Casual Sleeveless Stripe T Shirts Dres...,5.0,0,NaN,NaN,NaN,NaN,NaN
189,Jupe de tennis plissée extensible Active Skort...,5.0,0,NaN,NaN,NaN,NaN,NaN
216,Women's Sexy Push Up Bikini Sexy Vintage Set S...,5.0,0,NaN,NaN,NaN,NaN,NaN
248,Mode d'été Tie-Dye manches courtes robe longue...,5.0,0,NaN,NaN,NaN,NaN,NaN
309,Dames d'été Tie Dye Imprimer manches courtes h...,5.0,0,NaN,NaN,NaN,NaN,NaN
346,2020 New Women Summer Fashion O-neck Sleevele...,5.0,0,NaN,NaN,NaN,NaN,NaN
348,Combinaisons décontractées sans manches en cot...,5.0,0,NaN,NaN,NaN,NaN,NaN
375,Vintage Kawaii Harajuku T Shirt Women Ullzang ...,5.0,0,NaN,NaN,NaN,NaN,NaN
438,Women Off Shoulder Floral Print Boho Dress Wom...,5.0,0,NaN,NaN,NaN,NaN,NaN
447,Womens Summer Fashion Lip Print 2pc Set Ladies...,5.0,0,NaN,NaN,NaN,NaN,NaN
481,Femmes Crop Tops Deep V Neck Sans manches Slim...,5.0,0,NaN,NaN,NaN,NaN,NaN
487,Nouveau été hommes chat Caterpillar bulldozer ...,5.0,0,NaN,NaN,NaN,NaN,NaN
555,Femmes Robes D'été De Mode Col En V Dos Nu Rob...,5.0,0,NaN,NaN,NaN,NaN,NaN
597,Mode féminine Maillots de bain Deux pièces Spl...,5.0,0,NaN,NaN,NaN,NaN,NaN
618,Jupe de tennis plissée extensible Active Skort...,5.0,0,NaN,NaN,NaN,NaN,NaN
634,Gilet de couleur unie pour femmes à la mode d'...,5.0,0,NaN,NaN,NaN,NaN,NaN
670,2020 Femmes Mode Col En V Couleur Unie Slim Fi...,5.0,0,NaN,NaN,NaN,NaN,NaN
732,2020 New Women Summer Fashion O-neck Sleevele...,5.0,0,NaN,NaN,NaN,NaN,NaN
746,Mode féminine été bretelles spaghetti imprimé ...,5.0,0,NaN,NaN,NaN,NaN,NaN
774,Ventilateur personnel USB rechargeable mains l...,5.0,0,NaN,NaN,NaN,NaN,NaN
781,Hakuna Matata Lettre Imprimer Tee Shirt Été Fe...,5.0,0,NaN,NaN,NaN,NaN,NaN
864,8 Colors Plus Size Summer New Women Fashion La...,5.0,0,NaN,NaN,NaN,NaN,NaN
865,Papillon Imprimer Coton Masque Visage Sport En...,5.0,0,NaN,NaN,NaN,NaN,NaN
904,New Ladies Fashion Print Top Summer V-neck Sle...,5.0,0,NaN,NaN,NaN,NaN,NaN
959,New Ladies Fashion Print Top Summer V-neck Sle...,5.0,0,NaN,NaN,NaN,NaN,NaN
976,Été 2020 nouvelle robe lâche imprimé floral sa...,5.0,0,NaN,NaN,NaN,NaN,NaN
1094,Gilet de couleur unie pour femmes à la mode d'...,5.0,0,NaN,NaN,NaN,NaN,NaN
1117,New Ladies Fashion Print Top Summer V-neck Sle...,5.0,0,NaN,NaN,NaN,NaN,NaN
1127,Femmes Dames Mode Plus Size Daisy Sans Manches...,5.0,0,NaN,NaN,NaN,NaN,NaN
1148,Femmes Robes D'été De Mode Col En V Dos Nu Rob...,5.0,0,NaN,NaN,NaN,NaN,NaN
1156,Mens T-Shirts Summer Popular Tik Tok Printed ...,5.0,0,NaN,NaN,NaN,NaN,NaN
1186,Women Fashion Vintage Animal Dragonfly Owl Pri...,5.0,0,NaN,NaN,NaN,NaN,NaN
1190,Robe d'été sans manches imprimée sans bretelle...,5.0,0,NaN,NaN,NaN,NaN,NaN
1192,Robe d'été bohème à ourlet irrégulier à manche...,5.0,0,NaN,NaN,NaN,NaN,NaN
1242,Robe d'été sans manches imprimée sans bretelle...,5.0,0,NaN,NaN,NaN,NaN,NaN
1245,Dames d'été Tie Dye Imprimer manches courtes h...,5.0,0,NaN,NaN,NaN,NaN,NaN
1270,Papillon Imprimer Coton Masque Visage Sport En...,5.0,0,NaN,NaN,NaN,NaN,NaN
1292,T-shirt décontracté à manches courtes pour femmes,5.0,0,NaN,NaN,NaN,NaN,NaN
1355,Mode féminine été bretelles spaghetti imprimé ...,5.0,0,NaN,NaN,NaN,NaN,NaN
1468,Femmes Mode Sexy Tie Dye Imprimé Deux Pièces E...,5.0,0,NaN,NaN,NaN,NaN,NaN
1481,Mode féminine été bretelles spaghetti imprimé ...,5.0,0,NaN,NaN,NaN,NaN,NaN
1488,Nouvelles femmes d'été mode couleur unie short...,5.0,0,NaN,NaN,NaN,NaN,NaN
1532,6 Color Plus Size Women's Sexy Lace Patchwork ...,5.0,0,NaN,NaN,NaN,NaN,NaN

In [38]:
#STEP 3.15 — Inspect All Product Colors
sorted(
    df["product_color"]
    .dropna()
    .unique()
)

['Army green',
 'Black',
 'Blue',
 'Pink',
 'RED',
 'Rose red',
 'White',
 'applegreen',
 'apricot',
 'army',
 'army green',
 'armygreen',
 'beige',
 'black',
 'black & blue',
 'black & green',
 'black & stripe',
 'black & white',
 'black & yellow',
 'blackwhite',
 'blue',
 'blue & pink',
 'brown',
 'brown & yellow',
 'burgundy',
 'camel',
 'camouflage',
 'claret',
 'coffee',
 'coolblack',
 'coralred',
 'darkblue',
 'darkgreen',
 'denimblue',
 'dustypink',
 'floral',
 'fluorescentgreen',
 'gold',
 'gray',
 'gray & white',
 'green',
 'grey',
 'greysnakeskinprint',
 'ivory',
 'jasper',
 'khaki',
 'lakeblue',
 'leopard',
 'leopardprint',
 'light green',
 'lightblue',
 'lightgray',
 'lightgreen',
 'lightgrey',
 'lightkhaki',
 'lightpink',
 'lightpurple',
 'lightred',
 'lightyellow',
 'mintgreen',
 'multicolor',
 'navy',
 'navy blue',
 'navyblue',
 'navyblue & white',
 'nude',
 'offblack',
 'offwhite',
 'orange',
 'orange & camouflage',
 'orange-red',
 'pink',
 'pink & black',
 'pink & blue',
 'pink & grey',
 'pink & white',
 'prussianblue',
 'purple',
 'rainbow',
 'red',
 'red & blue',
 'rose',
 'rosegold',
 'rosered',
 'silver',
 'skyblue',
 'star',
 'tan',
 'violet',
 'watermelonred',
 'white',
 'white & black',
 'white & green',
 'white & red',
 'whitefloral',
 'whitestripe',
 'wine',
 'wine red',
 'winered',
 'winered & yellow',
 'yellow']

In [37]:
#3.16 — Check Shipping Categories
df["shipping_option_name"].value_counts(
    dropna=False
)

shipping_option_name
Livraison standard         1508
Standard Shipping            21
Envio Padrão                  9
Expediere Standard            6
Envío normal                  5
الشحن القياسي                 4
Standardversand               3
Standardowa wysyłka           3
Livraison Express             3
Стандартная доставка          3
Standart Gönderi              2
การส่งสินค้ามาตรฐาน           2
Spedizione standard           2
ការដឹកជញ្ជូនតាមស្តង់ដារ       1
Ekspresowa wysyłka            1
Name: count, dtype: int64

In [42]:
df.theme

0       summer
1       summer
2       summer
3       summer
4       summer
         ...
1568    summer
1569    summer
1570    summer
1571    summer
1572    summer
Name: theme, Length: 1573, dtype: str